apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-config
  namespace: practica-creativa
data:
  AIRFLOW__CORE__EXECUTOR: "LocalExecutor"
  AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://airflow:airflow@postgres.practica-creativa.svc.cluster.local:5432/airflow"
  AIRFLOW__CORE__LOAD_EXAMPLES: "false"
  AIRFLOW__CORE__FERNET_KEY: "eNW7wcd3cd3InwCIcsqO_kKo29XidorRZLGmYDdJ9I4="