apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-dags
  namespace: practica-creativa
data:
  train_model_lakehouse_dag.py: |
    from datetime import datetime
    from airflow import DAG
    from airflow.operators.empty import EmptyOperator

    with DAG(
        dag_id="train_model_lakehouse_dag",
        start_date=datetime(2026, 1, 1),
        schedule=None,
        catchup=False,
    ) as dag:
        start = EmptyOperator(task_id="start")